version: '3.8'

services:
  full-duplex-demo-backend:
    image: harbor.lightark.cc/iagent/full-duplex-demo-backend:500ac45-20250625-1543
    container_name: full-duplex-demo-backend
    ports:
      - "7860:7860"
    networks:
      - arkmind
    restart: always

  full-duplex-demo-frontend:
    image: harbor.lightark.cc/iagent/full-duplex-demo-frontend:836067a-20250625-1514
    container_name: full-duplex-demo-frontend
    ports:
      - "8080:80"
    depends_on:
      - full-duplex-demo-backend
    networks:
      - arkmind
    restart: always

networks:
  arkmind:
    driver: bridge 